### ISSUE TITLE
purpose of this hook ?

### ISSUE THREAD

**Issue by l1br3** [ghaiklor/sails-hook-acl#7]
Hi @ghaiklor, I'm currently looking into permissions for sails, there is the [sails-permissions](https://github.com/langateam/sails-permissions) module but as langateam is now focused on trails they won't update it anymore.

Does this hook will work with a permission service or is it just something to reload policies on the fly like sails-hoot-autoreload ? Or something else maybe ?

**Comment by ghaiklor** [comment]
@l1br3 this module is not developed. Guys promised to help me with this, though we didn't get through it. So, this hook\repo is unusable at all.

**Comment by l1br3** [comment]
But is it something which aim to manage role permissions ? I'm going to do something like this for one of my project so if you are interested we can share ideas to do it.

**Comment by l1br3** [comment]
Maybe something like this but without auth layer integrated in.
The config structure might also be different.

https://github.com/bgulotta/sails-hook-permit-actions

**Comment by l1br3** [comment]
Or this but with row level security
https://www.npmjs.com/package/sails-hook-user-acl

**Comment by ghaiklor** [comment]
@l1br3 I can transfer this repo to you and you can start working on it if you want :)

**Comment by l1br3** [comment]
Thats ok I've already got a repo for this with the name "sails-hook-role-permission".
In the sails doc there is a paragraph which says that sails has built in ACL when they speak about policies so I think that naming the hook ACL can be confusing. 
But I would be happy to make my hook compatible and similar to other sails-rest-api hooks. I woud dive into those ones and try to follow the same pattern.

**Comment by l1br3** [comment]
Finally this might be interesting to keep this repo as many things are already set up. We can change the name anyway

**Comment by l1br3** [comment]
I've made [this repo](https://github.com/l1br3/sails-hook-role-permissions) for the moment, we can merge it later if we want. At least hook is configured, initialized and tested.

**Comment by l1br3** [comment]
Hi @ghaiklor , job is done. Hook is made, documented and tested. Of course we need more tests, as always ;)
Could you give me your feedback on this ?

**Comment by ghaiklor** [comment]
@l1br3 I'll update my repo to refer to your repo, thanks 👍

**Comment by l1br3** [comment]
@ghaiklor  I guess that initially you wanted to include the hook in the generator ?

**Comment by ghaiklor** [comment]
@l1br3 yeah, I wanted and still want to. But I don't have time for this :(
I'll not argue if you want to add this into generator, I can help you with reviewing PR and sharing thoughts though :)

**Comment by l1br3** [comment]
@ghaiklor I really want to do it and I'm actually stabilizing the module for production use :)

**Comment by l1br3** [comment]
@ghaiklor Could you eventually give me feedback about the doc and open an issue if something isn't clear ?

**Comment by ghaiklor** [comment]
@l1br3 I don't see any issues with a documentation at least 👍 
Though, I hope, if you will integrate it into generator, would be great to have the whole flow, starting from questions about permissions in authentication section and finishing it with ready-to-go configuration :)
